Network:
  epochs: 300
  batch_size: 64
  n_steps: 5
  dataset: "CIFAR10"
  data_path: "../../datasets/cifar10"
  rule: "TSSLBP"
  lr: 0.0005
  loss: "kernel"
  n_class: 10
  desired_count: 5
  undesired_count: 1
  tau_m: 5
  tau_s: 3
  model: "LIF"

Layers:
  conv_1:
    type: "conv"   # 32*32  28*28
    in_channels: 3
    out_channels: 128
    kernel_size: 3
    weight_scale: 0.7
    padding: 1
    threshold: 1

    #dropout_1:
    #type: "dropout"
    #p: 0.2

  conv_2:
    type: "conv" # 32*32  28*28
    in_channels: 128
    out_channels: 256
    kernel_size: 3
    weight_scale: 0.9
    padding: 1
    threshold: 1

  pooling_1:
    type: "pooling"
    kernel_size: 2
    threshold: 0.5

  dropout_2:
    type: "dropout"
    p: 0.2

  conv_3:
    type: "conv" # 16*16  14*14
    in_channels: 256
    out_channels: 512
    kernel_size: 3
    weight_scale: 0.9
    padding: 1
    threshold: 1

  pooling_2:
    type: "pooling"
    kernel_size: 2
    threshold: 0.5

  dropout_3:
    type: "dropout"
    p: 0.2

  conv_4:
    type: "conv"  # 8*8  7*7
    in_channels: 512
    out_channels: 1024
    kernel_size: 3
    weight_scale: 0.9
    padding: 1
    threshold: 1

  dropout_4:
    type: "dropout"
    p: 0.2

  conv_5:
    type: "conv"  # 8*8  7*7
    in_channels: 1024
    out_channels: 512
    kernel_size: 3
    weight_scale: 3
    padding: 1
    threshold: 1

  dropout_5:
    type: "dropout"
    p: 0.2

  FC_1:
    type: "linear"
    n_inputs: 32768
    n_outputs: 2048
    weight_scale: 4
    threshold: 1

  dropout_6:
    type: "dropout"
    p: 0.5

  FC_2:
    type: "linear"
    n_inputs: 2048
    n_outputs: 1024
    weight_scale: 5
    threshold: 1

  dropout_7:
    type: "dropout"
    p: 0.5

  output:
    type: "linear"
    n_inputs: 1024
    n_outputs: 10
    weight_scale: 10
    threshold: 1

