Network:
  epochs: 200
  batch_size: 4
  n_steps: 100
  dataset: "CIFAR10_DVS"
  data_path: "../../datasets/CIFAR10_DVS"
  rule: "TSSLBP"
  lr: 0.0002
  loss: "count"
  n_class: 10
  desired_count: 35
  undesired_count: 5
  tau_m: 32
  tau_s: 8
  model: "LIF"

Layers:
  conv_1:
    type: "conv" # 40
    in_channels: 2
    out_channels: 128
    kernel_size: 3
    padding: 0
    threshold: 1

    # dropout_1:
    #   type: "dropout"
    #   p: 0.5

  conv_2: # 40
    type: "conv"
    in_channels: 128
    out_channels: 128
    kernel_size: 3
    padding: 1
    threshold: 1

  pooling_1:  # 20
    type: "pooling"
    kernel_size: 2
    threshold: 1

  conv_3:
    type: "conv" # 20
    in_channels: 128
    out_channels: 128
    kernel_size: 3
    padding: 1
    threshold: 1

  conv_4: # 20
    type: "conv"
    in_channels: 128
    out_channels: 256
    kernel_size: 3
    padding: 1
    threshold: 1

  pooling_2: # 10
    type: "pooling"
    kernel_size: 2
    threshold: 1

  # dropout_2:
  #   type: "dropout"
  #   p: 0.5
  
  hidden_1:
    type: "linear"
    n_inputs: 25600
    n_outputs: 1024
    threshold: 1


  output:
    type: "linear"
    n_inputs: 1024
    n_outputs: 10
    threshold: 1

