Network:
  epochs: 100
  batch_size: 50
  n_steps: 30
  dataset: "NMNIST_Spiking"
  rule: "TSSLBP"
  data_path: "../../datasets/mnist/2312_3000_stable"
  lr: 0.0005
  loss: "count"
  n_class: 10
  desired_count: 15
  undesired_count: 3
  tau_m: 8
  tau_s: 4
  model: "LIF"

Layers:
  conv_1:
    type: "conv" # 34
    in_channels: 2
    out_channels: 128
    kernel_size: 3
    weight_scale: 1
    padding: 1
    threshold: 1

  conv_2: # 34
    type: "conv"
    in_channels: 128
    out_channels: 128
    kernel_size: 3
    weight_scale: 1
    padding: 1
    threshold: 1
    
  pooling_1:  # 17
    type: "pooling"
    kernel_size: 2
    threshold: 0.5

  conv_3: # 17
    type: "conv"
    in_channels: 128
    out_channels: 384
    kernel_size: 3
    weight_scale: 1
    padding: 1
    threshold: 1

  conv_4:
    type: "conv" # 17
    in_channels: 384
    out_channels: 384
    kernel_size: 3
    weight_scale: 5
    padding: 1
    threshold: 1

  pooling_2: # 6
    type: "pooling"
    kernel_size: 2
    threshold: 0.5

  dropout_1:
    type: "dropout"
    p: 0.2

  FC_1:
    type: "linear"
    n_inputs: 16384
    n_outputs: 1024
    weight_scale: 1
    threshold: 1

  output:
    type: "linear"
    n_inputs: 2304
    n_outputs: 10
    weight_scale: 1
    threshold: 1

